# 3. A_total_normal 처리 후 TCP 통신 3개 미만 통신은 빼는 코드

In [1]:
import pandas as pd

In [2]:
oneway = pd.read_csv("test2_2nd_filter.csv", warn_bad_lines=False, error_bad_lines=False)

C:\Users\User\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3058: DtypeWarning: Columns (12,13,14,15,16,18,19,21) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [3]:
oneway['SET']=oneway['ip.src'].str.cat(oneway['ip.dst'].astype(str),sep=" ")

In [4]:
oneway

,_ws.col.UTCtime,_ws.col.Protocol,ip.src,ip.dst,tcp.srcport,tcp.dstport,tcp.len,tcp.seq,tcp.ack,udp.srcport,...,http.request.uri,http.user_agent,http.connection,http.host,http.response.code,http.server,http.content_type,http.content_length,http.cache_control,SET
0,12:00:55.330200,TCP,134.170.115.55,192.168.10.5,443.0,49176.0,0.0,0.0,1.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,134.170.115.55 192.168.10.5
1,12:00:55.419621,TCP,134.170.115.55,192.168.10.5,443.0,49176.0,0.0,1.0,190.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,134.170.115.55 192.168.10.5
2,12:01:20.252796,TCP,134.170.115.55,192.168.10.5,443.0,49176.0,2920.0,1.0,190.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,134.170.115.55 192.168.10.5
3,12:01:20.252991,TLSv1.2,134.170.115.55,192.168.10.5,443.0,49176.0,825.0,2921.0,190.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,134.170.115.55 192.168.10.5
4,12:01:20.336503,TCP,134.170.115.55,192.168.10.5,443.0,49176.0,0.0,3746.0,372.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,134.170.115.55 192.168.10.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3029048,16:29:42.253466,TCP,104.16.124.228,192.168.10.9,443.0,7118.0,0.0,1.0,518.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,104.16.124.228 192.168.10.9
3029049,16:29:42.253853,TLSv1.2,104.16.124.228,192.168.10.9,443.0,7118.0,162.0,1.0,518.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,104.16.124.228 192.168.10.9
3029050,16:29:42.269637,TCP,104.16.124.228,192.168.10.9,443.0,7118.0,0.0,163.0,1118.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,104.16.124.228 192.168.10.9
3029051,16:29:42.302729,TLSv1.2,104.16.124.228,192.168.10.9,443.0,7118.0,563.0,163.0,1118.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,104.16.124.228 192.168.10.9
3029052,16:29:42.302730,TLSv1.2,104.16.124.228,192.168.10.9,443.0,7118.0,34.0,726.0,1118.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,104.16.124.228 192.168.10.9

In [5]:
small = oneway['SET'].value_counts()

In [6]:
ssmall = small[small<3]

In [7]:
ssmall #### 결과가 0이면 우리가 뽑은 attack과 매우 유사함을 의미

38.69.238.113 192.168.10.8       2
52.216.20.179 192.168.10.15      2
129.146.13.96 192.168.10.8       2
149.6.126.132 192.168.10.16      2
52.209.203.172 192.168.10.12     2
209.48.71.161 192.168.10.12      2
151.101.21.181 192.168.10.19     2
52.18.141.29 192.168.10.12       2
23.199.171.46 192.168.10.12      2
169.55.70.175 192.168.10.8       2
103.224.182.245 192.168.10.12    2
104.192.110.216 192.168.10.16    2
34.199.153.0 192.168.10.5        2
103.235.252.231 192.168.10.19    2
209.48.71.138 192.168.10.12      2
151.101.65.34 192.168.10.15      2
172.217.12.193 192.168.10.16     2
23.208.92.92 192.168.10.15       2
146.186.157.6 192.168.10.19      2
172.217.12.138 192.168.10.16     2
52.216.228.16 192.168.10.5       2
151.101.64.204 192.168.10.19     2
52.216.64.160 192.168.10.12      2
172.217.12.193 192.168.10.8      2
209.48.71.242 192.168.10.12      2
208.185.118.99 192.168.10.19     2
151.101.192.204 192.168.10.19    2
50.18.50.60 192.168.10.17        2
54.209.247.112 192.168.10.16     2
209.48.71.250 192.168.10.12      2
151.101.128.204 192.168.10.19    2
173.192.200.113 192.168.10.12    2
104.24.107.213 192.168.10.12     2
131.253.34.246 192.168.10.3      2
209.48.71.120 192.168.10.9       2
188.165.232.92 192.168.10.14     2
52.216.20.251 192.168.10.15      2
151.101.0.204 192.168.10.19      2
52.2.143.27 192.168.10.17        2
210.140.236.10 192.168.10.25     1
103.224.182.245 192.168.10.25    1
198.84.60.134 192.168.10.12      1
210.140.236.11 192.168.10.25     1
210.140.236.12 192.168.10.25     1
69.64.147.32 192.168.10.19       1
174.129.29.90 192.168.10.25      1
Name: SET, dtype: int64

In [84]:
#### small의 값이 0이 나온경우 그만!!!!!!! 아래 코드 jmp
del oneway['SET']
oneway.to_csv("test2_1st_drop.csv",index=False, header=True)

In [8]:
ssmall.index[0].split(' ')[0]

'38.69.238.113'

In [9]:
a=[]
b=[]
for i in range(len(ssmall)):
    a.append(ssmall.index[i].split(' ')[0])
    b.append(ssmall.index[i].split(' ')[1])

In [10]:
df = pd.DataFrame({"ip.src":a,"ip.dst":b})

In [11]:
df

             ip.src         ip.dst
0     38.69.238.113   192.168.10.8
1     52.216.20.179  192.168.10.15
2     129.146.13.96   192.168.10.8
3     149.6.126.132  192.168.10.16
4    52.209.203.172  192.168.10.12
5     209.48.71.161  192.168.10.12
6    151.101.21.181  192.168.10.19
7      52.18.141.29  192.168.10.12
8     23.199.171.46  192.168.10.12
9     169.55.70.175   192.168.10.8
10  103.224.182.245  192.168.10.12
11  104.192.110.216  192.168.10.16
12     34.199.153.0   192.168.10.5
13  103.235.252.231  192.168.10.19
14    209.48.71.138  192.168.10.12
15    151.101.65.34  192.168.10.15
16   172.217.12.193  192.168.10.16
17     23.208.92.92  192.168.10.15
18    146.186.157.6  192.168.10.19
19   172.217.12.138  192.168.10.16
20    52.216.228.16   192.168.10.5
21   151.101.64.204  192.168.10.19
22    52.216.64.160  192.168.10.12
23   172.217.12.193   192.168.10.8
24    209.48.71.242  192.168.10.12
25   208.185.118.99  192.168.10.19
26  151.101.192.204  192.168.10.19
27      50.18.50.60  192.168.10.17
28   54.209.247.112  192.168.10.16
29    209.48.71.250  192.168.10.12
30  151.101.128.204  192.168.10.19
31  173.192.200.113  192.168.10.12
32   104.24.107.213  192.168.10.12
33   131.253.34.246   192.168.10.3
34    209.48.71.120   192.168.10.9
35   188.165.232.92  192.168.10.14
36    52.216.20.251  192.168.10.15
37    151.101.0.204  192.168.10.19
38      52.2.143.27  192.168.10.17
39   210.140.236.10  192.168.10.25
40  103.224.182.245  192.168.10.25
41    198.84.60.134  192.168.10.12
42   210.140.236.11  192.168.10.25
43   210.140.236.12  192.168.10.25
44     69.64.147.32  192.168.10.19
45    174.129.29.90  192.168.10.25

In [12]:
merge1 = oneway.merge(df, on=['ip.src','ip.dst'], how="outer",suffixes=['','_'],indicator=True)

In [13]:
merge1[merge1["_merge"]=="both"]

,_ws.col.UTCtime,_ws.col.Protocol,ip.src,ip.dst,tcp.srcport,tcp.dstport,tcp.len,tcp.seq,tcp.ack,udp.srcport,...,http.user_agent,http.connection,http.host,http.response.code,http.server,http.content_type,http.content_length,http.cache_control,SET,_merge
1632733,12:14:17.074047,TCP,103.224.182.245,192.168.10.12,443.0,42610.0,0.0,1.0,1.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,103.224.182.245 192.168.10.12,both
1632734,12:14:17.157227,TCP,103.224.182.245,192.168.10.12,443.0,42612.0,0.0,1.0,1.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,103.224.182.245 192.168.10.12,both
1699029,12:23:43.101162,TCP,174.129.29.90,192.168.10.25,443.0,49564.0,0.0,1.0,1.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,174.129.29.90 192.168.10.25,both
1712812,12:25:26.251486,TCP,54.209.247.112,192.168.10.16,80.0,42606.0,0.0,0.0,1.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,54.209.247.112 192.168.10.16,both
1712813,12:25:32.261063,TCP,54.209.247.112,192.168.10.16,80.0,42606.0,0.0,1.0,2.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,54.209.247.112 192.168.10.16,both
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2955423,15:19:41.710402,TCP,103.235.252.231,192.168.10.19,80.0,49604.0,0.0,1.0,2.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,103.235.252.231 192.168.10.19,both
2987237,16:09:12.879560,TCP,23.208.92.92,192.168.10.15,80.0,54239.0,0.0,0.0,1.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,23.208.92.92 192.168.10.15,both
2987238,16:09:18.015069,TCP,23.208.92.92,192.168.10.15,80.0,54239.0,0.0,1.0,2.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,23.208.92.92 192.168.10.15,both
2988841,16:11:19.000145,TCP,52.216.228.16,192.168.10.5,80.0,52640.0,0.0,0.0,1.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,52.216.228.16 192.168.10.5,both
2988842,16:11:24.611477,TCP,52.216.228.16,192.168.10.5,80.0,52640.0,0.0,1.0,2.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,52.216.228.16 192.168.10.5,both

In [14]:
merge1[merge1["_merge"]=="right_only"] # 없는거 확인

Empty DataFrame
Columns: [_ws.col.UTCtime, _ws.col.Protocol, ip.src, ip.dst, tcp.srcport, tcp.dstport, tcp.len, tcp.seq, tcp.ack, udp.srcport, udp.dstport, udp.length, http.request.method, http.request.uri, http.user_agent, http.connection, http.host, http.response.code, http.server, http.content_type, http.content_length, http.cache_control, SET, _merge]
Index: []

[0 rows x 24 columns]

In [15]:
handshake3 = merge1[merge1["_merge"]=="left_only"]

In [16]:
handshake3

,_ws.col.UTCtime,_ws.col.Protocol,ip.src,ip.dst,tcp.srcport,tcp.dstport,tcp.len,tcp.seq,tcp.ack,udp.srcport,...,http.user_agent,http.connection,http.host,http.response.code,http.server,http.content_type,http.content_length,http.cache_control,SET,_merge
0,12:00:55.330200,TCP,134.170.115.55,192.168.10.5,443.0,49176.0,0.0,0.0,1.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,134.170.115.55 192.168.10.5,left_only
1,12:00:55.419621,TCP,134.170.115.55,192.168.10.5,443.0,49176.0,0.0,1.0,190.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,134.170.115.55 192.168.10.5,left_only
2,12:01:20.252796,TCP,134.170.115.55,192.168.10.5,443.0,49176.0,2920.0,1.0,190.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,134.170.115.55 192.168.10.5,left_only
3,12:01:20.252991,TLSv1.2,134.170.115.55,192.168.10.5,443.0,49176.0,825.0,2921.0,190.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,134.170.115.55 192.168.10.5,left_only
4,12:01:20.336503,TCP,134.170.115.55,192.168.10.5,443.0,49176.0,0.0,3746.0,372.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,134.170.115.55 192.168.10.5,left_only
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3029048,16:29:38.237347,TLSv1,173.194.204.109,192.168.10.5,465.0,52840.0,85.0,4351.0,1305.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,173.194.204.109 192.168.10.5,left_only
3029049,16:29:38.286726,TCP,173.194.204.109,192.168.10.5,465.0,52840.0,0.0,4436.0,1379.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,173.194.204.109 192.168.10.5,left_only
3029050,16:29:38.287278,TLSv1,173.194.204.109,192.168.10.5,465.0,52840.0,85.0,4436.0,1379.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,173.194.204.109 192.168.10.5,left_only
3029051,16:29:38.287281,TCP,173.194.204.109,192.168.10.5,465.0,52840.0,0.0,4521.0,1379.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,173.194.204.109 192.168.10.5,left_only
3029052,16:29:38.336701,TCP,173.194.204.109,192.168.10.5,465.0,52840.0,0.0,4522.0,0.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,173.194.204.109 192.168.10.5,left_only

In [17]:
handshake3.to_csv("test2_1st_drop.csv",index=False, header=True)

# 3. B_total_normal 처리 후 TCP 통신 3개 미만 통신은 빼는 코드

In [42]:
oneway1 = pd.read_csv("B_test2_filter.csv", warn_bad_lines=False, error_bad_lines=False)

In [59]:
oneway1

,_ws.col.UTCtime,_ws.col.Protocol,ip.src,ip.dst,tcp.srcport,tcp.dstport,tcp.len,tcp.seq,tcp.ack,udp.srcport,...,http.request.uri,http.user_agent,http.connection,http.host,http.response.code,http.server,http.content_type,http.content_length,http.cache_control,SET
0,07:48:34.499147,TCP,222.104.14.117,10.89.32.47,53258.0,443.0,0.0,1.0,1.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,222.104.14.117 10.89.32.47
1,07:48:34.515154,TLSv1.2,222.104.14.117,10.89.32.47,53258.0,443.0,677.0,1.0,1.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,222.104.14.117 10.89.32.47
2,07:48:34.534202,TCP,222.104.14.117,10.89.32.47,53258.0,443.0,0.0,678.0,182.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,222.104.14.117 10.89.32.47
3,07:48:34.536717,TLSv1.2,222.104.14.117,10.89.32.47,53258.0,443.0,693.0,678.0,182.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,222.104.14.117 10.89.32.47
4,07:48:34.555843,TCP,222.104.14.117,10.89.32.47,53258.0,443.0,0.0,1371.0,363.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,222.104.14.117 10.89.32.47
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
156440,07:57:19.701809,TLSv1.2,211.179.209.170,10.89.32.66,46609.0,443.0,101.0,368.0,5156.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,211.179.209.170 10.89.32.66
156441,07:57:19.725196,TLSv1.2,211.179.209.170,10.89.32.66,46609.0,443.0,373.0,469.0,5263.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,211.179.209.170 10.89.32.66
156442,07:57:19.772626,TCP,211.179.209.170,10.89.32.66,46609.0,443.0,0.0,842.0,8183.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,211.179.209.170 10.89.32.66
156443,07:57:19.772910,TCP,211.179.209.170,10.89.32.66,46609.0,443.0,0.0,842.0,10196.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,211.179.209.170 10.89.32.66
156444,07:57:19.650428,TCP,51.77.192.7,10.89.32.94,32767.0,8545.0,0.0,0.0,0.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,51.77.192.7 10.89.32.94

In [43]:
oneway1.shape

(156445, 22)

In [44]:
oneway1['SET']=oneway1['ip.src'].str.cat(oneway1['ip.dst'].astype(str),sep=" ")

In [45]:
small = oneway1['SET'].value_counts()

In [46]:
ssmall = small[small<3]

In [47]:
ssmall #### 결과가 0이면 우리가 뽑은 attack과 매우 유사함을 의미

162.158.82.14 10.89.32.32     2
185.40.14.202 10.89.32.67     2
185.40.15.67 10.89.32.15      2
185.40.14.80 10.89.32.141     2
185.40.12.144 10.89.32.226    2
                             ..
185.40.12.62 10.89.32.249     1
59.148.60.94 10.89.32.226     1
185.40.15.245 10.89.32.196    1
93.174.93.136 10.89.32.58     1
71.6.167.142 10.89.32.108     1
Name: SET, Length: 8749, dtype: int64

In [25]:
#### small의 값이 0이 나온경우 그만!!!!!!! 아래 코드 jmp
del oneway1['SET']
oneway1.to_csv("B_test2_drop.csv",index=False, header=True)

In [48]:
ssmall.index[0].split(' ')[0]

'162.158.82.14'

In [49]:
a=[]
b=[]
for i in range(len(ssmall)):
    a.append(ssmall.index[i].split(' ')[0])
    b.append(ssmall.index[i].split(' ')[1])

In [50]:
df = pd.DataFrame({"ip.src":a,"ip.dst":b})

In [51]:
df

             ip.src        ip.dst
0     162.158.82.14   10.89.32.32
1     185.40.14.202   10.89.32.67
2      185.40.15.67   10.89.32.15
3      185.40.14.80  10.89.32.141
4     185.40.12.144  10.89.32.226
...             ...           ...
8744   185.40.12.62  10.89.32.249
8745   59.148.60.94  10.89.32.226
8746  185.40.15.245  10.89.32.196
8747  93.174.93.136   10.89.32.58
8748   71.6.167.142  10.89.32.108

[8749 rows x 2 columns]

In [52]:
merge1 = oneway1.merge(df, on=['ip.src','ip.dst'], how="outer",suffixes=['','_'],indicator=True)

In [53]:
merge1[merge1["_merge"]=="both"]

,_ws.col.UTCtime,_ws.col.Protocol,ip.src,ip.dst,tcp.srcport,tcp.dstport,tcp.len,tcp.seq,tcp.ack,udp.srcport,...,http.user_agent,http.connection,http.host,http.response.code,http.server,http.content_type,http.content_length,http.cache_control,SET,_merge
13458,07:48:34.543495,TCP,185.40.13.191,10.89.32.156,57051.0,4434.0,0.0,0.0,0.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,185.40.13.191 10.89.32.156,both
13459,07:48:34.544606,TCP,92.118.37.95,10.89.32.49,46862.0,3582.0,0.0,0.0,0.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,92.118.37.95 10.89.32.49,both
13460,07:48:34.560339,TCP,185.40.12.33,10.89.32.157,50949.0,3128.0,0.0,0.0,0.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,185.40.12.33 10.89.32.157,both
13461,07:48:34.582132,TCP,185.40.15.168,10.89.32.109,63012.0,4434.0,0.0,0.0,0.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,185.40.15.168 10.89.32.109,both
14068,07:48:34.621406,TCP,185.40.15.69,10.89.32.239,45116.0,3128.0,0.0,0.0,0.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,185.40.15.69 10.89.32.239,both
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
156440,07:57:17.313469,TCP,185.176.27.170,10.89.32.202,45739.0,26770.0,0.0,0.0,0.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,185.176.27.170 10.89.32.202,both
156441,07:57:17.558522,TCP,46.150.253.50,10.89.32.231,64831.0,9001.0,0.0,0.0,0.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,46.150.253.50 10.89.32.231,both
156442,07:57:17.643307,TCP,51.91.212.81,10.89.32.89,57824.0,993.0,0.0,0.0,0.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,51.91.212.81 10.89.32.89,both
156443,07:57:19.440065,TCP,80.82.70.239,10.89.32.155,55984.0,10600.0,0.0,0.0,0.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,80.82.70.239 10.89.32.155,both
156444,07:57:19.650428,TCP,51.77.192.7,10.89.32.94,32767.0,8545.0,0.0,0.0,0.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,51.77.192.7 10.89.32.94,both

In [54]:
merge1[merge1["_merge"]=="right_only"] # 없는거 확인

Empty DataFrame
Columns: [_ws.col.UTCtime, _ws.col.Protocol, ip.src, ip.dst, tcp.srcport, tcp.dstport, tcp.len, tcp.seq, tcp.ack, udp.srcport, udp.dstport, udp.length, http.request.method, http.request.uri, http.user_agent, http.connection, http.host, http.response.code, http.server, http.content_type, http.content_length, http.cache_control, SET, _merge]
Index: []

[0 rows x 24 columns]

In [55]:
handshake3 = merge1[merge1["_merge"]=="left_only"]

In [56]:
handshake3

,_ws.col.UTCtime,_ws.col.Protocol,ip.src,ip.dst,tcp.srcport,tcp.dstport,tcp.len,tcp.seq,tcp.ack,udp.srcport,...,http.user_agent,http.connection,http.host,http.response.code,http.server,http.content_type,http.content_length,http.cache_control,SET,_merge
0,07:48:34.499147,TCP,222.104.14.117,10.89.32.47,53258.0,443.0,0.0,1.0,1.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,222.104.14.117 10.89.32.47,left_only
1,07:48:34.515154,TLSv1.2,222.104.14.117,10.89.32.47,53258.0,443.0,677.0,1.0,1.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,222.104.14.117 10.89.32.47,left_only
2,07:48:34.534202,TCP,222.104.14.117,10.89.32.47,53258.0,443.0,0.0,678.0,182.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,222.104.14.117 10.89.32.47,left_only
3,07:48:34.536717,TLSv1.2,222.104.14.117,10.89.32.47,53258.0,443.0,693.0,678.0,182.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,222.104.14.117 10.89.32.47,left_only
4,07:48:34.555843,TCP,222.104.14.117,10.89.32.47,53258.0,443.0,0.0,1371.0,363.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,222.104.14.117 10.89.32.47,left_only
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
156381,07:57:18.025255,TCP,152.99.253.15,10.89.32.47,54994.0,443.0,0.0,2018.0,17426.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,152.99.253.15 10.89.32.47,left_only
156382,07:57:18.025257,TCP,152.99.253.15,10.89.32.47,54994.0,443.0,0.0,2018.0,17426.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,152.99.253.15 10.89.32.47,left_only
156383,07:57:18.186934,TCP,152.99.253.15,10.89.32.47,54994.0,443.0,0.0,2018.0,30566.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,152.99.253.15 10.89.32.47,left_only
156384,07:57:18.364552,TCP,152.99.253.15,10.89.32.47,54994.0,443.0,0.0,2018.0,32469.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,152.99.253.15 10.89.32.47,left_only
156385,07:57:18.364976,TLSv1.2,152.99.253.15,10.89.32.47,54994.0,443.0,521.0,2018.0,32469.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,152.99.253.15 10.89.32.47,left_only

In [61]:
handshake3.to_csv("B_test2_drop.csv",index=False, header=True)

In [63]:
len(oneway1)

156445